#ifndef FACE_RECOG_FLYCAPTURE2_DEFINE_H
#define FACE_RECOG_FLYCAPTURE2_DEFINE_H

#include "CameraDefines.h"

#ifndef FACE_RECOG_HAS_FLYCAPTURE2
#define FACE_RECOG_HAS_FLYCAPTURE2 0
#elif defined(FACE_RECOG_HAS_FLYCAPTURE2)
#if FACE_RECOG_HAS_FLYCAPTURE2 == 1
#include "FlyCapture2Utilities.h"
#endif/*FACE_RECOG_HAS_FLYCAPTURE2 == 1*/
#endif/*FACE_RECOG_HAS_FLYCAPTURE2*/

#endif /*FACE_RECOG_FLYCAPTURE2_DEFINE_H*/
